---
kind: pipeline
name: build

steps:
- name: "set image tags"
  image: alpine
  environment:
    VERSION: "7.2.10-r2"
  commands:
    - "./write-tags.sh $VERSION > .tags"
    - "# Will build the following tags:"
    - "cat .tags"

- name: "build docker image"
  image: plugins/docker
  settings:
    repo: ovdnet/atheme
    username:
      from_secret: docker_user
    password:
      from_secret: docker_password
    build_args:
      - ATHEME_VERSION=7.2.10-r2
  trigger:
    branch:
    - master

---
kind: pipeline
name: build-contrib

steps:
- name: "set image tags"
  image: alpine
  environment:
    VERSION: "7.2.10-r2"
  commands:
    - "./write-tags.sh $VERSION contrib > .tags"
    - "# Will build the following tags:"
    - "cat .tags"

- name: "build docker image"
  image: plugins/docker
  settings:
    repo: ovdnet/atheme
    username:
      from_secret: docker_user
    password:
      from_secret: docker_password
    build_args:
      - ATHEME_VERSION=7.2.10-r2
      - BUILD_CONTRIB_MODULES=true
  trigger:
    branch:
    - master
