---
kind: pipeline
name: default

steps:
- name: "set image tags (normal build)"
  image: alpine
  environment:
    VERSION: "7.2.10-r2"
  commands:
    - "./write-tags.sh $VERSION > .tags"
    - "echo Will build the following tags:"
    - "cat .tags"

- name: "build docker image"
  image: plugins/docker
  settings:
    repo: ovdnet/atheme
    username:
      from_secret: docker_user
    password:
      from_secret: docker_password
    build_args:
      - VERSION=7.2.10-r2
  trigger:
    branch:
    - master

- name: "set image tags (build with contrib)"
  image: alpine
  environment:
    VERSION: "7.2.10-r2"
  commands:
    - "./write-tags.sh $VERSION contrib > .tags"
    - "echo Will build the following tags:"
    - "cat .tags"

- name: "build docker image (contrib)"
  image: plugins/docker
  settings:
    repo: ovdnet/atheme
    username:
      from_secret: docker_user
    password:
      from_secret: docker_password
    build_args:
      - VERSION=7.2.10-r2
      - BUILD_CONTRIB_MODULES=true
  trigger:
    branch:
    - master
