---
kind: pipeline
name: build

platform:
  os: linux
  arch: amd64

steps:
- name: set image tags
  image: alpine
  commands:
  - ./write-tags.sh $VERSION contrib > .tags
  - "# Will build the following tags:"
  - cat .tags
  environment:
    VERSION: 7.2.10-r2

- name: build docker image
  image: ovdnet/drone-docker
  settings:
    build_args:
    - ATHEME_VERSION=7.2.10-r2
    password:
      from_secret: docker_password
    repo: ovdnet/atheme
    username:
      from_secret: docker_user
  volumes:
  - name: docker-socket
    path: /var/run/docker.sock

volumes:
- name: docker-socket
  host:
    path: /var/run/docker.sock

---
kind: pipeline
name: build-contrib

platform:
  os: linux
  arch: amd64

steps:
- name: set image tags
  image: alpine
  commands:
  - ./write-tags.sh $VERSION contrib > .tags
  - "# Will build the following tags:"
  - cat .tags
  environment:
    VERSION: 7.2.10-r2

- name: build docker image
  image: ovdnet/drone-docker
  settings:
    build_args:
    - ATHEME_VERSION=7.2.10-r2
    - BUILD_CONTRIB_MODULES=true
    password:
      from_secret: docker_password
    repo: ovdnet/atheme
    username:
      from_secret: docker_user
  volumes:
  - name: docker-socket
    path: /var/run/docker.sock

volumes:
- name: docker-socket
  host:
    path: /var/run/docker.sock

...
