---
kind: pipeline
name: build

steps:
- name: "set image tags"
  image: alpine
  environment:
    VERSION: "7.2.10-r2"
  commands:
    - "./write-tags.sh $VERSION > .tags"
    - "# Will build the following tags:"
    - "cat .tags"

- name: "build docker image"
  # Basically plugins/docker but bumped to Docker v20.10.7 for Alpine 3.14 support
  # See https://github.com/drone-plugins/drone-docker/issues/326
  image: ovdnet/drone-docker
  settings:
    repo: ovdnet/atheme
    username:
      from_secret: docker_user
    password:
      from_secret: docker_password
    build_args:
      - ATHEME_VERSION=7.2.10-r2
  trigger:
    branch:
    - master
  volumes:
  - name: docker-socket
    path: /var/run/docker.sock

volumes:
- name: docker-socket
  host:
    path: /var/run/docker.sock

---
kind: pipeline
name: build-contrib

steps:
- name: "set image tags"
  image: alpine
  environment:
    VERSION: "7.2.10-r2"
  commands:
    - "./write-tags.sh $VERSION contrib > .tags"
    - "# Will build the following tags:"
    - "cat .tags"

- name: "build docker image"
  image: ovdnet/drone-docker
  settings:
    repo: ovdnet/atheme
    username:
      from_secret: docker_user
    password:
      from_secret: docker_password
    build_args:
      - ATHEME_VERSION=7.2.10-r2
      - BUILD_CONTRIB_MODULES=true
  trigger:
    branch:
    - master
  volumes:
  - name: docker-socket
    path: /var/run/docker.sock

volumes:
- name: docker-socket
  host:
    path: /var/run/docker.sock
